; Generated by atelier-theme — do not edit (switch themes instead)
[colors]
background = {{ background }}
background-alt = {{ background_alt }}
foreground = {{ foreground }}
primary = {{ accent }}
secondary = {{ magenta }}
alert = {{ red }}
disabled = {{ comment }}
green = {{ green }}
yellow = {{ yellow }}
cyan = {{ cyan }}
