# Generated by matugen via atelier-theme from-wallpaper
name=Generated
mode={{ mode }}

background={{ colors.surface.default.hex }}
background_alt={{ colors.surface_container.default.hex }}
background_deep={{ colors.surface_container_lowest.default.hex }}
foreground={{ colors.on_surface.default.hex }}
foreground_dim={{ colors.on_surface_variant.default.hex }}
comment={{ colors.outline.default.hex }}
border={{ colors.outline_variant.default.hex }}
accent={{ colors.primary.default.hex }}
red={{ colors.error.default.hex }}
green={{ colors.tertiary.default.hex }}
yellow={{ colors.tertiary_fixed.default.hex }}
blue={{ colors.primary.default.hex }}
magenta={{ colors.secondary.default.hex }}
cyan={{ colors.secondary_container.default.hex }}
orange={{ colors.error_container.default.hex }}

cursor={{ colors.on_surface.default.hex }}
selection_background={{ colors.primary_container.default.hex }}
selection_foreground={{ colors.on_primary_container.default.hex }}

color0={{ colors.surface_container_highest.default.hex }}
color1={{ colors.error.default.hex }}
color2={{ colors.tertiary.default.hex }}
color3={{ colors.tertiary_fixed.default.hex }}
color4={{ colors.primary.default.hex }}
color5={{ colors.secondary.default.hex }}
color6={{ colors.secondary_container.default.hex }}
color7={{ colors.on_surface_variant.default.hex }}
color8={{ colors.outline_variant.default.hex }}
color9={{ colors.error.default.hex }}
color10={{ colors.tertiary.default.hex }}
color11={{ colors.tertiary_fixed.default.hex }}
color12={{ colors.primary.default.hex }}
color13={{ colors.secondary.default.hex }}
color14={{ colors.secondary_container.default.hex }}
color15={{ colors.on_surface.default.hex }}
