# Generated by atelier-theme — sourced from bspwmrc
ATELIER_BG='{{ background }}'
ATELIER_BORDER_NORMAL='{{ color8 }}'
ATELIER_BORDER_ACTIVE='{{ accent }}'
ATELIER_BORDER_FOCUSED='{{ accent }}'
ATELIER_PRESEL='{{ magenta }}'
