# Generated by atelier-theme — sourced from ~/.xinitrc
export GTK_THEME='{{ gtk_theme }}'
export XCURSOR_THEME=Yaru
export XCURSOR_SIZE=24
export ATELIER_COLOR_SCHEME='{{ color_scheme }}'
export ATELIER_ICON_THEME='{{ icon_theme }}'
