/* Generated by atelier-theme — do not edit (switch themes instead) */
@define-color atelier_bg {{ background }};
@define-color atelier_bg_alt {{ background_alt }};
@define-color atelier_bg_deep {{ background_deep }};
@define-color atelier_fg {{ foreground }};
@define-color atelier_fg_dim {{ foreground_dim }};
@define-color atelier_blue {{ accent }};
@define-color atelier_magenta {{ magenta }};
@define-color atelier_red {{ red }};
@define-color atelier_green {{ green }};
@define-color atelier_comment {{ comment }};
@define-color atelier_border {{ border }};
