/* Generated by atelier-theme — do not edit (switch themes instead) */
* {
	bg:       {{ background }};
	bg-alt:   {{ background_alt }};
	fg:       {{ foreground }};
	fg-alt:   {{ comment }};
	blue:     {{ accent }};
	magenta:  {{ magenta }};
	red:      {{ red }};
	green:    {{ green }};

	background-color: @bg;
	text-color:       @fg;
}

window {
	width: 40%;
	border: 2px;
	border-color: @blue;
	border-radius: 0;
	padding: 12px;
	background-color: @bg;
	transparency: "real";
}

mainbox {
	children: [ inputbar, listview ];
	spacing: 10px;
	background-color: @bg;
}

inputbar {
	children: [ prompt, entry ];
	padding: 8px;
	background-color: @bg-alt;
	border-radius: 0;
	spacing: 8px;
	text-color: @fg;
}

prompt {
	enabled: true;
	background-color: transparent;
	text-color: @blue;
}

entry {
	placeholder: "Search…";
	placeholder-color: @fg-alt;
	background-color: transparent;
	text-color: @fg;
	cursor: text;
	blink: true;
}

listview {
	lines: 10;
	scrollbar: false;
	spacing: 4px;
	background-color: @bg;
	cycle: true;
	dynamic: true;
	fixed-height: true;
}

element {
	padding: 8px;
	border-radius: 0;
	background-color: @bg;
	text-color: @fg;
}

element selected {
	background-color: @bg-alt;
	text-color: @blue;
}

element-icon {
	size: 1.2em;
	background-color: transparent;
}

element-text {
	background-color: transparent;
	text-color: inherit;
	highlight: bold {{ accent }};
	vertical-align: 0.5;
}
