# Generated by atelier-theme — source from scripts / bashrc
ATELIER_BG='{{ background }}'
ATELIER_FG='{{ foreground }}'
ATELIER_ACCENT='{{ accent }}'
COLOR_UP='{{ green }}'
COLOR_DOWN='{{ red }}'
ATELIER_MODE='{{ mode }}'
