# Generated by atelier-theme from the Atelier starship template.
# Override: ~/.config/atelier/templates/starship.toml.tpl

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

add_newline = true

[character]
success_symbol = "[❯](bold {{ accent }})"
error_symbol = "[❯](bold {{ red }})"
vicmd_symbol = "[❮](bold {{ green }})"

[directory]
style = "bold {{ cyan }}"
truncation_length = 3
truncate_to_repo = true

[username]
style_user = "bold {{ magenta }}"
style_root = "bold {{ red }}"
format = "[$user]($style) "
show_always = false

[hostname]
ssh_only = true
style = "bold {{ yellow }}"
format = "at [$hostname]($style) "

[git_branch]
symbol = " "
style = "bold {{ magenta }}"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold {{ red }}"
format = '([\[$all_status$ahead_behind\]]($style) )'

[cmd_duration]
min_time = 2000
style = "bold {{ yellow }}"
format = "took [$duration]($style) "
