# Generated by atelier-theme — sourced from xsecurelock/env.sh
export XSECURELOCK_AUTH_BACKGROUND_COLOR="{{ background }}"
export XSECURELOCK_AUTH_FOREGROUND_COLOR="{{ foreground }}"
export XSECURELOCK_BACKGROUND_COLOR="{{ background_deep }}"
